name: menu_qr
description: "A new Flutter project."
publish_to: 'none'

# ADD THESE THREE LINES:
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3

  # State Management
  provider: ^6.1.2

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

  # QR
  qr_flutter: ^4.1.0

  # Utils
  image_picker: ^1.1.2
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true